### ISSUE TITLE
iOS Webview Device ID

### ISSUE THREAD

**Issue by mechiles** [humhub-contrib/fcm-push#4]
I've created an app using a Webview wrapper with Humhub. I have FCM enabled and it's working for web and Android push notifications, however, I don't see a good way to get the device ID from iOS to put into the fcmpush database. Any way of doing this? If I plug my iPhone in and run the build from Xcode to it, I can get the device ID, put it into the database and I do get the push notifications on my iPhone. Just need a way to extract that without the manual effort.

**Comment by luke-** [comment]
On Android the ID is added using a POST to http://example.com/fcm-push/token/update with POST data `token`. Did you tried this?

**Comment by mechiles** [comment]
Hey @luke- thanks for getting back to me. I'm not sure how it would be any different when logging into the app on iOS. The code is still set to update the token but doesn't get it with iOS. I think it has to do with it being a webview wrapper app and not passing the token back through. I'm not sure if there is a way to do this.

**Comment by luke-** [comment]
Unfortunately, I don't know much about it either. I only know that the token can be written into the database via the update action.

**Comment by steffes** [comment]
@mechiles check out this issue https://github.com/humhub/humhub-modules-fcm-push/issues/1

**Comment by mechiles** [comment]
Thanks @steffes. I'm hoping to not have to build an entire app.... At least at the moment.

**Comment by mechiles** [comment]
@steffes would you be interested in sharing your app code or open-sourcing it, without any of your intellectual property in it?

**Comment by JK742020** [comment]
@steffes did I understand right that you built an app to get notifications from humhub on iOS and android? How does it work from an end user's point of view? Is it available on github or for sale? I am a bit frustrated about humhub not having pushnotifications the users are used to from other mobile apps. Looking forward to hearing from you! Thanks. Jürgen

**Comment by steffes** [comment]
@JK742020 I was forced to build an iOS app in order to get push notifications. On Android, you can add HumHub to your homescreen as a PWA and can receive WebPush Notifications.

I built a Xamarin iOS app that required an unreasonable amount of steps to get to the default functionality of an Android PWA with WebPush Notifications. Unfortunately I can't release code at the moment (not my choice) @samuk @mechiles .

Here is a sample list of steps:

- Enroll in Apple Developer Program for $99
- Get a physical iOS device. Remote notifications not allowed in iOS Simulator 
- Create Apple Push Notification Service Certificate, iOS Distribution Certificate (App Store)
- Create an [App Group](https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/provisioning/capabilities/app-groups-capabilities) with Push Notifications enabled
- install fcm-push and [rest](https://github.com/humhub/rest) humhub module in HumHub
- refactor [swagger yaml](https://github.com/humhub/rest/tree/master/docs/swagger) within rest module to OpenAPI 3.0 to [enable jwt](https://github.com/humhub/rest/pull/10)
- use the swagger cli to dereference the yaml files into 1 file
```bash
npm install swagger-cli -g
swagger-cli bundle --dereference activity.yaml --outfile activity.json
```
- convert swagger 2.0 to OpenAPI 3.0 with [Mermade Swagger Converter](https://mermade.org.uk/openapi-converter)
- use nswag to transform json into csharp client service 
```bash
nswag swagger2csclient /input:activity.json /classname:ActivityService /namespace:CustomHumHub.Services /output:../ActivityService.cs
```
- Create a Xamarin.iOS project including a Notification Content Extension and Notification Service Extension

https://docs.microsoft.com/en-us/xamarin/ios/platform/user-notifications/advanced-user-notifications?tabs=macos
Here is a Xamarin.iOS sample app for notifications
https://docs.microsoft.com/en-us/samples/xamarin/ios-samples/ios10-monkeynotify/

**Comment by JK742020** [comment]
thanks steffens!
